### ISSUE TITLE
frida.InvalidOperationError: script is destroyed

### ISSUE THREAD

**Issue by yuzhouheike** [ChiChou/frida-ipa-dump#1]
```

Hades:frida-ipa-dump-master Hades$ python3 dump.py com.tencent.xin
[info] attaching to target
[info] decrypting module WeChat
[info] decrypting module TXLiteAVSDK_Smart_No_VOD
[info] decrypting module WCDB
[info] decrypting module MMCommon
[info] decrypting module MultiMedia
[info] decrypting module QMapKit
[info] decrypting module mars
Traceback (most recent call last):
  File "dump.py", line 175, in <module>
    main()
  File "dump.py", line 172, in main
    dump(args.app, args.device, args.verbose)
  File "dump.py", line 43, in dump
    task.run()
  File "dump.py", line 158, in run
    self.inject()
  File "dump.py", line 153, in inject
    script.exports.dump()
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 442, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 372, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed

```

**Comment by ChiChou** [comment]
Start the app first then retry, if you keep seeing this.

**Comment by ChiChou** [comment]
This is due to the stability of app itself or some unknown crash of frida framework

**Comment by yuzhouheike** [comment]
thank you!
