### ISSUE TITLE
IPA generated doesn't have the right structure

### ISSUE THREAD

**Issue by hduarte** [ChiChou/frida-ipa-dump#10]
The IPA generated is a zip file with a few of the contents of the original IPA and without the correct structure.

appname.ipa:
 Payload
  appname.app
   ...

The frameworks folder is not being created with the already decrypted ones.

**Comment by ChiChou** [comment]
fixed https://github.com/ChiChou/frida-ipa-dump/commit/1255a9452b9b3ac46bf5ed5be4d98f4cfda612a6

**Comment by ptr-ptr** [comment]
ipad mini 4 ios 9.0
dump encrypt ipa the correct :
[info] decrypting module kofficeCore
Traceback (most recent call last):
  File "dump.py", line 246, in <module>
    main()
  File "dump.py", line 242, in main
    task.run()
  File "dump.py", line 220, in run
    self.dump()
  File "dump.py", line 159, in dump
    self.dump_with_plugins()
  File "dump.py", line 179, in dump_with_plugins
    pid = self.script.exports.launch(identifier)
  File "C:\Python27\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "C:\Python27\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: <exception str() failed>
