### ISSUE TITLE
Error when dumping plugins

### ISSUE THREAD

**Issue by h0ng10** [ChiChou/frida-ipa-dump#17]
I had an issue when I tried to dump a iOS application that had plugins. 

Environment:  
- iOS: 12.4.0
- Device: iPhone SE
- Frida version: 12.6.18

Here the shortened command line output. I'm not allowed to provide the name/id of the actual app:
```
frida-ipa-dump h0ng10$ ./dump.py app-with-plugins
[info] attaching to target
[info] decrypting module xxxxxx
...
[info] decrypting module AppBusinessLogic
plugin com.xxxx.yyyyyy.zzzzServiceExtension, pid=1497
Traceback (most recent call last):
  File "./dump.py", line 253, in <module>
    main()
  File "./dump.py", line 249, in main
    task.run()
  File "./dump.py", line 227, in run
    self.dump()
  File "./dump.py", line 162, in dump
    self.dump_with_plugins()
  File "./dump.py", line 185, in dump_with_plugins
    script = session.create_script(self.agent_source)
  File "/Library/Python/2.7/site-packages/frida/core.py", line 148, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: the connection is closed
```

**Comment by ChiChou** [comment]
I've rewritten everything. It should be working now
