### ISSUE TITLE
dump plugin    frida.InvalidOperationError: script is destroyed   

### ISSUE THREAD

**Issue by yonglefu** [ChiChou/frida-ipa-dump#21]
plugin com.tencent.xin.siriextension, pid=2187

Traceback (most recent call last):
  File "dump.py", line 257, in <module>
    main()
  File "dump.py", line 253, in main
    task.run()
  File "dump.py", line 228, in run
    self.dump()
  File "dump.py", line 163, in dump
    self.dump_with_plugins()
  File "dump.py", line 190, in dump_with_plugins
    decrypted += script.exports.decrypt(self.root)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 327, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed

**Comment by yonglefu** [comment]
fixed by h0ng10/frida-ipa-dump
