### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

### ISSUE THREAD

**Issue by zljkevin** [ChiChou/frida-ipa-dump#7]
$ python /Users/mu/Desktop/frida-ipa-dump-master/dump.py com.laiwang.DingTalk 
Traceback (most recent call last):
  File "/Users/mu/Desktop/frida-ipa-dump-master/dump.py", line 215, in <module>
    main()
  File "/Users/mu/Desktop/frida-ipa-dump-master/dump.py", line 212, in main
    task.run()
  File "/Users/mu/Desktop/frida-ipa-dump-master/dump.py", line 175, in run
    with tempfile.TemporaryDirectory() as tempdir:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

**Comment by ChiChou** [comment]
Only python3 is supported
